### ISSUE TITLE
virtualenv change

### ISSUE THREAD

**Issue by TheBrandonMorris** [0Hughman0/RamCal#4]
When running `virtualenv --python=python3 --no-site-packages env`, the error  `virtualenv: error: unrecognized arguments: --no-site-packages SystemExit: 2` occurs. This is likely due to the removal of `--no-site-packages' as it is made default.

**Comment by 0Hughman0** [comment]
Hey Brandon,

Thanks for the heads up. As you might be able to tell, this is an ancient project for me.

But thanks for the kick up the backside - I've just updated the venv and dependencies to be managed by Pipenv.

Hopefully this will make the project a bit more future-proof! 

Hugh
